remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

title: Mo Rajabi
logo: /assets/img/img.jpg
description: Writes about code, life and everything in between.

# Optional extras
show_downloads: false
