# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mo (Mohammad) Rajabi B.
title: Computer Engineering Student
email: mohammad.rajabi.ba@gmail.com
website: mo-rajabi.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: mo-rajabi
linkedin_username: mo-rajabi

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Mo. I'm a computer engineering student interested in AI/ML.  
  I also enjoy teaching and have experience sharing my knowledge with others.  

  My strongest skills are: <mark>Linux</mark> and <mark>Python</mark>.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: ProjectEuler Solutions
        link: https://github.com/mo-rajabi/projecteuler-solutions
        description: |
          I started this project to practice problem-solving and apply theoretical
          mathematics in programming.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Freelance
        sub_title: Code and Mathematics Teacher
        caption: November 2023 - Present
        quote: >
          One of the greatest experiences I’ve had is helping someone truly
          understand a concept—especially when it’s as challenging as programming or math.
        description: |
          I taught private lessons to teenagers and adults on problem-solving—
          sometimes with pen and paper, sometimes with code and keyboard.

  - title: Education
    layout: list
    content:
      - layout: left
        title: IAUN
        caption: 2024 - Present
        sub_title: B.Sc. Computer Engineering
        quote: >
          I once participated in the National Olympiad in Informatics. Due to family
          challenges, including my father’s cancer, I couldn’t study or code properly
          during high school. Coming to university helped me return to the right path.
        description: |
          I’m still studying and working on building valuable connections. I’m also
          planning to translate books and conduct extra research during my studies.

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in software engineering, some of my other hobbies are:
      - Boxing (hardcore)
      - Reading books (mostly philosophy)
      - Playing chess

# Footer
footer_show_references: true
# references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
