# Site settings
repository: mo-rajabi/mo-rajabi.github.io
remote_theme: sproogen/modern-resume-theme

# Personal info
name: Mo Rajabi
title: Computer Engineering Student
email: mohammad.rajabi.ba@gmail.comm
website: https://mo-rajabi.github.io

# Social links
github_username: mo-rajabi
linkedin_username: mo-rajabi
# twitter_username: your_twitter
# instagram_username: your_instagram

# About section
about_content: |
  I am a computer engineering student passionate about coding, startups, and creating solutions.  
  I enjoy writing about code, life, and everything in between.

# Theme settings
darkmode: true   # Options: true, false, never
